### ISSUE TITLE
Possible to run it for Bitcoin?

### ISSUE THREAD

**Issue by GaloisField2718** [afomi/livewallet#1]
Hello,

I noticed that your repo is built with BSV package. Are you working on a Bitcoin mainnet version? I suppose that it can be done with some RPC and bip32 libs.

**Comment by afomi** [comment]
@GaloisField2718 - I'm open to that.

What specific features are you looking for?

---

I'll be exploring a few different chains casually in the next 2 months:

binance, near, cardano

**Comment by GaloisField2718** [comment]
Oh cool. Near has a good cli: near-cli-rs. I really recommend it. For Cardano, I'll get some info soon I can come back to you if I get some info
